// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-tournaments.ts
import { createClient } from "npm:@supabase/supabase-js@^2.81.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_tournaments_default = defineTool({
  name: "list_tournaments",
  title: "Listar torneos",
  description: "Devuelve los torneos (eventos) de FEMD Eventos ordenados por fecha descendente. \xDAtil para saber qu\xE9 torneos existen, cu\xE1ndo se juegan y d\xF3nde.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("M\xE1ximo de torneos a devolver (por defecto 20)."),
    upcoming_only: z.boolean().optional().describe("Si es true, solo devuelve torneos cuya fecha final es hoy o posterior.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, upcoming_only }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("events").select("id, title, date, end_date, location, description, poster_url").order("date", { ascending: false }).limit(limit ?? 20);
    if (upcoming_only) {
      const today = (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
      query = query.gte("date", today);
    }
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { tournaments: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-tournament-standings.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.81.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_tournament_standings_default = defineTool2({
  name: "get_tournament_standings",
  title: "Clasificaci\xF3n de un torneo",
  description: "Devuelve la clasificaci\xF3n (grupos) de un torneo dado por su id. Incluye equipos, puntos, PJ, PG/PE/PP, GF/GC, DG y tarjetas.",
  inputSchema: {
    event_id: z2.string().uuid().describe("ID del torneo (events.id)."),
    category_id: z2.string().uuid().optional().describe("ID opcional de categor\xEDa para filtrar solo esa categor\xEDa.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ event_id, category_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado." }], isError: true };
    }
    const supabase = supabaseForUser2(ctx);
    let q = supabase.from("event_teams").select(
      "id, group_name, points, matches_played, wins, draws, losses, goals_for, goals_against, goal_difference, yellow_cards, red_cards, team_id, category_id, teams(name, logo_url), categories(name)"
    ).eq("event_id", event_id).order("group_name", { ascending: true }).order("points", { ascending: false });
    if (category_id) q = q.eq("category_id", category_id);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { standings: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-live-matches.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.81.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^4.4.3";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_live_matches_default = defineTool3({
  name: "list_live_matches",
  title: "Partidos en vivo",
  description: "Devuelve los partidos actualmente en juego (status = 'in_progress') con marcador, equipos y torneo. Opcionalmente filtra por evento.",
  inputSchema: {
    event_id: z3.string().uuid().optional().describe("ID del torneo para filtrar. Si se omite, devuelve todos los partidos en vivo.")
  },
  annotations: { readOnlyHint: true, idempotentHint: false, openWorldHint: false },
  handler: async ({ event_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado." }], isError: true };
    }
    const supabase = supabaseForUser3(ctx);
    let q = supabase.from("matches").select(
      "id, event_id, phase, group_name, match_date, started_at, status, home_score, away_score, home_team_id, away_team_id, home_placeholder, away_placeholder, events(title), home:teams!matches_home_team_id_fkey(name), away:teams!matches_away_team_id_fkey(name)"
    ).eq("status", "in_progress").order("started_at", { ascending: false }).limit(50);
    if (event_id) q = q.eq("event_id", event_id);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { matches: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/search-teams.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.81.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^4.4.3";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var search_teams_default = defineTool4({
  name: "search_teams",
  title: "Buscar equipos / clubes",
  description: "Busca equipos o clubes por coincidencia parcial en el nombre. Devuelve id, nombre, categor\xEDa y logo.",
  inputSchema: {
    query: z4.string().trim().min(1).describe("Texto a buscar en el nombre del equipo."),
    limit: z4.number().int().min(1).max(50).optional().describe("M\xE1ximo de resultados (por defecto 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado." }], isError: true };
    }
    const supabase = supabaseForUser4(ctx);
    const { data, error } = await supabase.from("teams").select("id, name, logo_url, parent_team_id, team_group").ilike("name", `%${query}%`).order("name", { ascending: true }).limit(limit ?? 20);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { teams: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-my-profile.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.81.1";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
function supabaseForUser5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_my_profile_default = defineTool5({
  name: "get_my_profile",
  title: "Mi perfil",
  description: "Devuelve el perfil del usuario autenticado en FEMD Eventos (id, email, nombre) y sus roles asignados (admin, mesa, moderator, user).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado." }], isError: true };
    }
    const userId = ctx.getUserId();
    const email = ctx.getUserEmail();
    const supabase = supabaseForUser5(ctx);
    const { data: rolesData } = await supabase.from("user_roles").select("role").eq("user_id", userId);
    const profile = {
      id: userId,
      email,
      roles: (rolesData ?? []).map((r) => r.role)
    };
    return {
      content: [{ type: "text", text: JSON.stringify(profile, null, 2) }],
      structuredContent: { profile }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "zftbjgonactnpkbkdawh";
var mcp_default = defineMcp({
  name: "femd-eventos-mcp",
  title: "FEMD Eventos MCP",
  version: "0.1.0",
  instructions: "Herramientas de FEMD Eventos: consulta torneos, clasificaciones, partidos en vivo, equipos y tu propio perfil. Todas las llamadas se ejecutan como el usuario autenticado y respetan sus permisos.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_tournaments_default,
    get_tournament_standings_default,
    list_live_matches_default,
    search_teams_default,
    get_my_profile_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
